# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
  jobs:
    post_checkout:
      - conda activate rtd_env
      - pip install --upgrade pip ipython ipykernel
      - ipython kernel install --name "python3" --user

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc_build/conf.py

conda:
  environment: doc_build/rtd_env.yml

sphinx:
  fail_on_warning: true

formats: []

#build:
#  commands: 
#    - conda activate rtd_env

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#   install:
#   - requirements: docs/requirements.txt
