#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 25 05:41:33 2020

@author: deborahkhider

Pyleoclim workflows: curated  functions using a datasert object (either lipd
or user supplied)
"""

